blank_issues_enabled: false
contact_links:
    - name: Questions & support
      url: https://github.com/seventwos-app/usr-workspace-desktop/issues
      about: Please open an issue with the details of your question.
